export const labels = {
  appName: 'OHealth Demo',
  common: {
    viewAll: 'Lihat semua',
    continue: 'Lanjutkan',
    confirm: 'Konfirmasi',
    cancel: 'Batal',
    backHome: 'Kembali ke Beranda',
  },
  tabs: {
    home: 'Home',
    appointments: 'Appointment',
    profile: 'Profile',
  },
  home: {
    title: 'Dashboard',
    greeting: 'Selamat datang kembali',
    tagline: 'Semua layanan sudah siap untuk demo hari ini.',
    quickActionsTitle: 'Aksi Cepat',
    servicesTitle: 'Layanan Populer',
    appointmentsTitle: 'Jadwal Terdekat',
  },
  actions: {
    bookAppointment: 'Booking Appointment',
    browseServices: 'Lihat Layanan',
    chatDoctor: 'Chat Dokter',
    supportCenter: 'Pusat Bantuan',
    callCenter: 'Hubungi CS',
  },
  booking: {
    title: 'Booking Appointment',
    subtitle: 'Pilih layanan dan jadwal yang paling nyaman.',
    chooseService: 'Pilih Layanan',
    chooseDoctor: 'Pilih Dokter',
    chooseDate: 'Pilih Tanggal',
    chooseTime: 'Pilih Waktu',
    addNotes: 'Catatan Tambahan',
    notesPlaceholder: 'Contoh: keluhan selama 2 hari terakhir',
  },
  appointments: {
    title: 'Appointment Saya',
    subtitle: 'Semua appointment demo sudah tersusun rapi.',
    upcoming: 'Upcoming',
    history: 'Riwayat',
    reschedule: 'Ubah Jadwal',
  },
  profile: {
    title: 'Profil',
    subtitle: 'Data Anda siap untuk demo lengkap.',
    membership: 'Membership',
    membershipLevel: 'Gold',
    editProfile: 'Ubah Profil',
    notifications: 'Notifikasi',
    paymentMethod: 'Metode Pembayaran',
    emailLabel: 'Email',
    phoneLabel: 'Telepon',
  },
  success: {
    title: 'Booking Berhasil',
    message: 'Appointment Anda sudah tersimpan dan siap ditampilkan di demo.',
    viewAppointments: 'Lihat Appointment',
  },
  modal: {
    title: 'Informasi Demo',
    description: 'Fitur tambahan siap ditunjukkan kapan saja.',
    backHome: 'Kembali ke Beranda',
  },
  stack: {
    booking: 'Booking',
    success: 'Berhasil',
    modal: 'Modal',
  },
};
