export const labels = {
    auth: {
        loginTitle: 'Masuk ke Akun Anda',
        usernameOrEmailPlaceholder: 'Masukkan Username atau Email',
        passwordPlaceholder: 'Masukkan Kata Sandi',
        forgotPassword: 'Lupa Password?',
        loginButton: 'Masuk',
        registerPrompt: 'Belum punya akun? Daftar di sini.',
        missingCredentials: 'Mohon isi email dan password',
        invalidCredentials: 'Email/Username atau password salah',
        demoUserName: 'Test User',
        demoAddress: 'Test Address',
        registerTitle: 'Daftar Akun Baru',
        fullNameLabel: 'Nama Lengkap',
        fullNamePlaceholder: 'Masukkan Nama Lengkap',
        contactLabel: 'Email / No. HP',
        contactPlaceholder: 'Masukkan Email atau Nomor Telepon',
        usernameLabel: 'Username',
        usernamePlaceholder: 'Buat Username',
        registerPasswordLabel: 'Password',
        registerPasswordPlaceholder: 'Pilih Kata Sandi',
        passwordHint: 'Minimal 6 karakter',
        birthDateLabel: 'Tanggal Lahir',
        birthDatePlaceholder: 'YYYY-MM-DD (Contoh: 1990-01-31)',
        genderLabel: 'Jenis Kelamin',
        maleLabel: 'Laki-laki',
        femaleLabel: 'Perempuan',
        addressLabel: 'Alamat Lengkap',
        addressPlaceholder: 'Masukkan Alamat Lengkap',
        bpjsLabel: 'Nomor BPJS (Opsional)',
        bpjsPlaceholder: 'Masukkan Nomor BPJS',
        registerButton: 'Daftar',
        existingAccountPrompt: 'Sudah punya akun?',
        registerSuccessTitle: 'Pendaftaran Berhasil',
        registerSuccessMessage: 'Akun Anda telah berhasil dibuat. Silakan masuk dengan akun baru Anda.',
        registerErrorTitle: 'Gagal Daftar',
        registerOkButton: 'OK',
        forgotPasswordTitle: 'Lupa Password',
        forgotPasswordDescription:
            'Masukkan alamat email yang terdaftar untuk menerima tautan reset password.',
        forgotPasswordEmailLabel: 'Email',
        forgotPasswordEmailPlaceholder: 'nama@email.com',
        forgotPasswordSendButton: 'Kirim Tautan Reset',
        forgotPasswordAlertTitle: 'Perhatian',
        forgotPasswordAlertMessage: 'Mohon masukkan email anda.',
        forgotPasswordSuccessTitle: 'Berhasil',
        forgotPasswordSuccessMessage: 'Tautan reset password telah dikirim ke email anda.',
        backToLogin: 'Kembali Login',
    },
    home: {
        guestName: 'Tamu',
        greeting: (name: string) => `Halo, ${name} 👋`,
        subGreeting: 'Semoga sehat selalu!',
        searchPlaceholder: 'Cari dokter, spesialis, atau klinik...',
        bannerTitle: 'Lengkapi Data Diri',
        bannerDescription:
            'Pastikan data BPJS dan rekam medis Anda terupdate untuk pelayanan lebih cepat.',
        bannerButton: 'Perbarui Sekarang',
        mainServicesTitle: 'Layanan Utama',
        quickActionTitle: 'Pesan Lagi',
        seeAll: 'Lihat Semua',
        healthInfoTitle: 'Info Kesehatan',
        bookLabel: 'Pesan',
        infoBedTitle: 'Info',
        infoBedMessage: 'Fitur Info Bed belum tersedia.',
        hospitalName: 'RSUD Oto Iskandar Dinata',
        bookingButton: 'Daftar Janji Temu Online',
        rebookTitle: 'Pesan Ulang',
        reminderTitle: 'Pengingat Janji Temu',
        noReminder: 'Belum ada janji temu mendatang.',
        bpjsStatusLabel: 'Status BPJS Anda:',
        bpjsActiveStatus: 'AKTIF',
        helpCenter: 'Pusat Bantuan',
    },
    searchDoctor: {
        title: 'Temukan Dokter & Spesialis',
        searchPlaceholder: 'Cari Nama Dokter atau Spesialisasi...',
        bookButton: 'Buat Janji Temu',
        filterSpecialty: 'Spesialisasi',
        filterLocation: 'Lokasi',
        filterSchedule: 'Jadwal',
        applyFilter: 'Terapkan Filter',
        ratingLabel: 'Rating',
        seeDetail: 'Lihat Detail',
        doctorDetailTitle: 'Profil Lengkap Dokter',
        doctorDescription: 'Tentang Dokter',
        educationTitle: 'Pendidikan',
        experienceTitle: 'Pengalaman Kerja',
        reviewTitle: 'Rating & Ulasan',
        reviewCount: (count: number) => `(${count} Ulasan)`,
        seeAllReviews: 'Lihat Semua Ulasan',
        practiceSchedule: 'Jadwal Praktek',
        availableStatus: 'Tersedia',
        fullStatus: 'Penuh',
        practiceLocation: 'Lokasi & Kontak',
        viewMap: 'Lihat di Peta',
        hospitalPhone: 'Hubungi Rumah Sakit',
        searchEmpty: 'Maaf, dokter tidak ditemukan.',
        askDoctor: 'Tanya Dokter',
    },
    booking: {
        headerTitle: 'Buat Janji Temu',
        selectDate: 'Pilih Tanggal',
        selectTime: 'Pilih Waktu',
        confirmPersonalData: 'Konfirmasi Data Diri',
        edit: 'Ubah',
        done: 'Selesai',
        fullName: 'Nama Lengkap',
        phone: 'Nomor Telepon',
        bpjs: 'Nomor BPJS',
        nik: 'NIK (Nomor Induk Kependudukan)',
        address: 'Alamat Lengkap',
        nikPlaceholder: 'Masukkan 16 digit NIK',
        invalidNik: 'Nomor NIK tidak valid (harus 16 digit)',
        summaryTitle: 'Ringkasan Pemesanan',
        emptyTime: 'Belum pilih waktu',
        confirmButton: 'Konfirmasi Janji Temu',
        attentionTitle: 'Perhatian',
        attentionMessage: 'Mohon pilih jam praktek.',
        confirmTitle: 'Konfirmasi Pemesanan',
        cancel: 'Batal',
        confirm: 'Konfirmasi',
        doctorLabel: 'Dokter',
        dateLabel: 'Tanggal',
        timeLabel: 'Jam',
    },
    appointmentSuccess: {
        title: 'Pemesanan Berhasil!',
        subtitle: 'Tunjukkan QR Code ini di rumah sakit untuk verifikasi pendaftaran.',
        orderLabel: 'No. Pesanan',
        alertText: 'QR Code ini hanya berlaku untuk satu kali pemesanan.',
        downloadButton: 'Unduh QR Code',
        shareButton: 'Kirim ke Email',
        downloadSuccessTitle: 'Berhasil',
        downloadSuccessMessage: 'QR Code berhasil diunduh ke galeri.',
        shareSuccessTitle: 'Berhasil',
        shareSuccessMessage: 'QR Code dikirim ke email Anda.',
        backHome: 'Kembali ke Beranda',
        qrTitle: 'QR Code Verifikasi Janji Temu',
        verifyInstruction: 'Tunjukkan QR Code ini di rumah sakit untuk verifikasi',
        validityReminder: 'QR Code ini hanya berlaku untuk satu kali pemesanan.',
        nikLabel: 'NIK',
        backToHistory: 'Lihat Riwayat Janji Temu',
        bookingConfirmMessage: 'Janji temu Anda berhasil dipesan. QR Code Anda akan ditampilkan di halaman berikutnya.',
    },
    helpCenter: {
        registrationTitle: 'Panduan Daftar Online',
        registrationContent: '1. Buka halaman Beranda.\n2. Klik tombol "Cari Dokter".\n3. Pilih spesialisasi dan dokter yang diinginkan.\n4. Pilih tanggal yang tersedia.\n5. Konfirmasi data diri dan klik Pesan.',
        bpjsTitle: 'Panduan Layanan BPJS',
        bpjsContent: 'Untuk menggunakan layanan BPJS, pastikan:\n- Anda membawa kartu BPJS/KIS asli.\n- Memiliki rujukan dari Faskes Tingkat 1.\n- Data NIK sesuai dengan KTP elektronik.',
        scheduleTitle: 'Informasi Jadwal Dokter',
        scheduleContent: 'Jadwal dokter dapat berubah sewaktu-waktu. Untuk informasi real-time, silakan cek menu "Cari Dokter" dan pilih dokter spesialis terkait untuk melihat jam praktek terbaru.',
        contactTitle: 'Hubungi Kami',
        contactContent: 'Alamat: Jl. Raya Soreang No. 1 Bandung\nTelepon: (022) 1234567\nEmail: info@rsudoto.id',
        urgentTitle: 'Bantuan Mendesak',
        urgentContent: 'Untuk kondisi darurat/IGD, silakan hubungi Call Center 24 Jam kami di 119 atau (022) 999999.',
    },
    history: {
        title: 'Janji Temu Saya',
        upcomingSection: 'Janji Temu Mendatang',
        pastSection: 'Riwayat Kunjungan',
        emptyUpcoming: 'Belum ada janji temu mendatang.',
        emptyPast: 'Belum ada riwayat kunjungan.',
        cancelButton: 'Batalkan',
        changeButton: 'Ubah Jadwal',
        viewDetail: 'Lihat Detail',
        diagnosisLabel: 'Diagnosis/Layanan',
        paymentStatusPaid: 'Sudah Dibayar',
        paymentStatusPending: 'Menunggu Pembayaran',
        cancelConfirmTitle: 'Batalkan Janji Temu',
        cancelConfirmMessage: 'Apakah Anda yakin ingin membatalkan janji temu ini?',
        qrDetailTitle: 'Detail & Verifikasi',
        downloadQR: 'Simpan QR Code',
        shareQR: 'Bagikan QR',
        bookingRestriction: 'Pemesanan hanya tersedia untuk hari ini dan besok.',
    },
    profile: {
        title: 'Pengaturan',
        defaultName: 'Pengguna',
        defaultPhone: '0812-XXXX-XXXX',
        personalDataTitle: 'Data Pribadi',
        birthDate: 'Tanggal Lahir',
        gender: 'Jenis Kelamin',
        address: 'Alamat',
        male: 'Laki-laki',
        female: 'Perempuan',
        bpjsTitle: 'Data BPJS',
        bpjsUpdate: 'Perbarui Status',
        bpjsUpdating: 'Memperbarui...',
        bpjsActive: 'AKTIF',
        defaultBpjsNumber: '0000 0000 0000 0000',
        emptyValue: '-',
        settingsTitle: 'Pengaturan',
        logout: 'Keluar Aplikasi',
        logoutTitle: 'Konfirmasi Keluar',
        logoutMessage: 'Apakah Anda yakin ingin keluar dari aplikasi?',
        logoutCancel: 'Batal',
        logoutConfirm: 'Keluar',
        refreshSuccessTitle: 'Sukses',
        refreshSuccessMessage: 'Data BPJS berhasil diperbarui.',
        medicalRecordMessage: 'Fitur Rekam Medis akan segera hadir',
        medicalRecordTitle: 'Rekam Medis',
        phone: 'Nomor Telepon',
        paymentTitle: 'Info',
        paymentMessage: 'Fitur Metode Pembayaran akan segera hadir',
        editLabel: 'Edit',
        updateLabel: 'Perbarui',
        medicalHistoryTitle: 'Riwayat Medis',
        allergies: 'Alergi',
        bloodType: 'Golongan Darah',
        medicalNotes: 'Riwayat Penyakit',
        emergencyContact: 'Kontak Darurat',
        bpjsAlert: 'Perbarui nomor BPJS Anda untuk memastikan akses ke layanan BPJS.',
        changePasswordLabel: 'Ubah Kata Sandi',
        securityTitle: 'Keamanan & Pengaturan',
    },
    editProfile: {
        title: 'Edit Profil',
        fullName: 'Nama Lengkap',
        phone: 'Nomor Telepon',
        birthDate: 'Tanggal Lahir',
        birthDatePlaceholder: 'Contoh: 31 Januari 1990',
        gender: 'Jenis Kelamin',
        address: 'Alamat',
        allergies: 'Alergi',
        bloodType: 'Golongan Darah',
        medicalHistory: 'Riwayat Penyakit',
        saveButton: 'Simpan Perubahan',
        successTitle: 'Sukses',
        successMessage: 'Profil berhasil diperbarui.',
    },
    changePassword: {
        title: 'Ubah Kata Sandi',
        currentPassword: 'Kata Sandi Saat Ini',
        newPassword: 'Kata Sandi Baru',
        confirmPassword: 'Konfirmasi Kata Sandi Baru',
        saveButton: 'Simpan Password',
        errorTitle: 'Error',
        emptyMessage: 'Mohon isi semua kolom.',
        mismatchMessage: 'Password baru dan konfirmasi tidak cocok.',
        lengthMessage: 'Password minimal 6 karakter.',
        successTitle: 'Sukses',
        successMessage: 'Password berhasil diubah.',
        ok: 'OK',
    },
    notifications: {
        title: 'Notifikasi',
        emptyMessage: 'Belum ada notifikasi.',
    },
    misc: {
        modalTitle: 'Ini adalah modal',
        modalLink: 'Kembali ke beranda',
    },
};
