export const labels = {
    auth: {
        loginTitle: 'Masuk ke Akun Anda',
        usernameOrEmailPlaceholder: 'Masukkan Username atau Email',
        passwordPlaceholder: 'Masukkan Kata Sandi',
        forgotPassword: 'Lupa Password?',
        loginButton: 'Masuk',
        registerPrompt: 'Belum punya akun? Daftar di sini.',
        missingCredentials: 'Mohon isi email dan password',
        invalidCredentials: 'Email/Username atau password salah',
        demoUserName: 'Test User',
        demoAddress: 'Test Address',
        registerTitle: 'Daftar Akun Baru',
        fullNameLabel: 'Nama Lengkap',
        fullNamePlaceholder: 'Masukkan Nama Lengkap',
        contactLabel: 'Email / No. HP',
        contactPlaceholder: 'Masukkan Email atau Nomor Telepon',
        usernameLabel: 'Username',
        usernamePlaceholder: 'Buat Username',
        registerPasswordLabel: 'Password',
        registerPasswordPlaceholder: 'Pilih Kata Sandi',
        passwordHint: 'Minimal 6 karakter',
        birthDateLabel: 'Tanggal Lahir',
        birthDatePlaceholder: 'YYYY-MM-DD (Contoh: 1990-01-31)',
        genderLabel: 'Jenis Kelamin',
        maleLabel: 'Laki-laki',
        femaleLabel: 'Perempuan',
        addressLabel: 'Alamat Lengkap',
        addressPlaceholder: 'Masukkan Alamat Lengkap',
        bpjsLabel: 'Nomor BPJS (Opsional)',
        bpjsPlaceholder: 'Masukkan Nomor BPJS',
        registerButton: 'Daftar',
        existingAccountPrompt: 'Sudah punya akun?',
        registerSuccessTitle: 'Pendaftaran Berhasil',
        registerSuccessMessage: 'Akun Anda telah berhasil dibuat. Silakan masuk dengan akun baru Anda.',
        registerErrorTitle: 'Gagal Daftar',
        registerOkButton: 'OK',
        forgotPasswordTitle: 'Lupa Password',
        forgotPasswordDescription:
            'Masukkan alamat email yang terdaftar untuk menerima tautan reset password.',
        forgotPasswordEmailLabel: 'Email',
        forgotPasswordEmailPlaceholder: 'nama@email.com',
        forgotPasswordSendButton: 'Kirim Tautan Reset',
        forgotPasswordAlertTitle: 'Perhatian',
        forgotPasswordAlertMessage: 'Mohon masukkan email anda.',
        forgotPasswordSuccessTitle: 'Berhasil',
        forgotPasswordSuccessMessage: 'Tautan reset password telah dikirim ke email anda.',
        backToLogin: 'Kembali Login',
    },
    home: {
        guestName: 'Tamu',
        greeting: (name: string) => `Halo, ${name} 👋`,
        subGreeting: 'Semoga sehat selalu!',
        searchPlaceholder: 'Cari dokter, spesialis, atau klinik...',
        bannerTitle: 'Lengkapi Data Diri',
        bannerDescription:
            'Pastikan data BPJS dan rekam medis Anda terupdate untuk pelayanan lebih cepat.',
        bannerButton: 'Perbarui Sekarang',
        mainServicesTitle: 'Layanan Utama',
        quickActionTitle: 'Pesan Lagi',
        seeAll: 'Lihat Semua',
        healthInfoTitle: 'Info Kesehatan',
        bookLabel: 'Pesan',
        infoBedTitle: 'Info',
        infoBedMessage: 'Fitur Info Bed belum tersedia.',
    },
    searchDoctor: {
        title: 'Cari Dokter',
        searchPlaceholder: 'Nama dokter atau spesialis...',
        bookButton: 'Buat Janji',
    },
    booking: {
        headerTitle: 'Buat Janji Temu',
        selectDate: 'Pilih Tanggal',
        selectTime: 'Pilih Waktu',
        confirmPersonalData: 'Konfirmasi Data Diri',
        edit: 'Ubah',
        done: 'Selesai',
        fullName: 'Nama Lengkap',
        phone: 'Nomor Telepon',
        bpjs: 'Nomor BPJS',
        summaryTitle: 'Ringkasan Pemesanan',
        emptyTime: 'Belum pilih waktu',
        confirmButton: 'Konfirmasi Janji Temu',
        attentionTitle: 'Perhatian',
        attentionMessage: 'Mohon pilih jam praktek.',
        confirmTitle: 'Konfirmasi Pemesanan',
        cancel: 'Batal',
        confirm: 'Konfirmasi',
        doctorLabel: 'Dokter',
        dateLabel: 'Tanggal',
        timeLabel: 'Jam',
    },
    appointmentSuccess: {
        title: 'Pemesanan Berhasil!',
        subtitle: 'Tunjukkan QR Code ini di rumah sakit untuk verifikasi pendaftaran.',
        orderLabel: 'No. Pesanan',
        alertText: 'QR Code ini hanya berlaku untuk satu kali pemesanan.',
        downloadButton: 'Unduh QR Code',
        shareButton: 'Kirim ke Email',
        downloadSuccessTitle: 'Berhasil',
        downloadSuccessMessage: 'QR Code berhasil diunduh ke galeri.',
        shareSuccessTitle: 'Berhasil',
        shareSuccessMessage: 'QR Code dikirim ke email Anda.',
        backHome: 'Kembali ke Beranda',
    },
    history: {
        title: 'Riwayat Janji Temu',
        emptyMessage: 'Belum ada riwayat janji temu.',
    },
    profile: {
        title: 'Pengaturan',
        defaultName: 'Pengguna',
        defaultPhone: '0812-XXXX-XXXX',
        personalDataTitle: 'Data Pribadi',
        birthDate: 'Tanggal Lahir',
        gender: 'Jenis Kelamin',
        address: 'Alamat',
        male: 'Laki-laki',
        female: 'Perempuan',
        bpjsTitle: 'Data BPJS',
        bpjsUpdate: 'Perbarui Status',
        bpjsUpdating: 'Memperbarui...',
        bpjsActive: 'AKTIF',
        defaultBpjsNumber: '0000 0000 0000 0000',
        emptyValue: '-',
        settingsTitle: 'Pengaturan',
        logout: 'Keluar Aplikasi',
        logoutTitle: 'Konfirmasi Keluar',
        logoutMessage: 'Apakah Anda yakin ingin keluar dari aplikasi?',
        logoutCancel: 'Batal',
        logoutConfirm: 'Keluar',
        refreshSuccessTitle: 'Sukses',
        refreshSuccessMessage: 'Data BPJS berhasil diperbarui.',
        medicalRecordTitle: 'Info',
        medicalRecordMessage: 'Fitur Rekam Medis akan segera hadir',
        paymentTitle: 'Info',
        paymentMessage: 'Fitur Metode Pembayaran akan segera hadir',
    },
    editProfile: {
        title: 'Edit Profil',
        fullName: 'Nama Lengkap',
        phone: 'Nomor Telepon',
        birthDate: 'Tanggal Lahir',
        birthDatePlaceholder: 'Contoh: 31 Januari 1990',
        gender: 'Jenis Kelamin',
        address: 'Alamat',
        saveButton: 'Simpan Perubahan',
        successTitle: 'Sukses',
        successMessage: 'Profil berhasil diperbarui.',
    },
    changePassword: {
        title: 'Ubah Kata Sandi',
        currentPassword: 'Kata Sandi Saat Ini',
        newPassword: 'Kata Sandi Baru',
        confirmPassword: 'Konfirmasi Kata Sandi Baru',
        saveButton: 'Simpan Password',
        errorTitle: 'Error',
        emptyMessage: 'Mohon isi semua kolom.',
        mismatchMessage: 'Password baru dan konfirmasi tidak cocok.',
        lengthMessage: 'Password minimal 6 karakter.',
        successTitle: 'Sukses',
        successMessage: 'Password berhasil diubah.',
        ok: 'OK',
    },
    notifications: {
        title: 'Notifikasi',
        emptyMessage: 'Belum ada notifikasi.',
    },
    misc: {
        modalTitle: 'Ini adalah modal',
        modalLink: 'Kembali ke beranda',
    },
};
