import { Platform, StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
    container: {
        flex: 1,
        backgroundColor: '#F8F9FA',
    },
    content: {
        padding: 20,
        paddingBottom: 100,
    },
    doctorHeader: {
        flexDirection: 'row',
        alignItems: 'center',
        backgroundColor: '#fff',
        padding: 20,
        borderRadius: 16,
        marginBottom: 24,
        borderWidth: 1,
        borderColor: '#F1F3F5',
    },
    avatarLarge: {
        width: 70,
        height: 70,
        borderRadius: 35,
        backgroundColor: '#E3F2FD',
        justifyContent: 'center',
        alignItems: 'center',
        marginRight: 16,
    },
    doctorInfo: {
        flex: 1,
    },
    docName: {
        fontSize: 18,
        fontWeight: 'bold',
        color: '#333',
        marginBottom: 4,
    },
    docSpecialist: {
        fontSize: 14,
        color: '#666',
        marginBottom: 4,
    },
    docHospital: {
        fontSize: 12,
        color: '#999',
    },
    section: {
        backgroundColor: '#fff',
        padding: 20,
        borderRadius: 16,
        marginBottom: 20,
        borderWidth: 1,
        borderColor: '#F1F3F5',
    },
    sectionHeader: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
        marginBottom: 16,
    },
    sectionTitle: {
        fontSize: 16,
        fontWeight: 'bold',
        color: '#333',
    },
    calendarScroll: {
        marginHorizontal: -10,
    },
    dateCard: {
        width: 65,
        height: 80,
        justifyContent: 'center',
        alignItems: 'center',
        backgroundColor: '#F8F9FA',
        borderRadius: 12,
        marginHorizontal: 8,
        borderWidth: 1,
        borderColor: '#E9ECEF',
    },
    dateCardActive: {
        backgroundColor: '#2196F3',
        borderColor: '#2196F3',
    },
    dayText: {
        fontSize: 12,
        color: '#666',
        marginBottom: 6,
    },
    dateText: {
        fontSize: 20,
        fontWeight: 'bold',
        color: '#333',
    },
    textActive: {
        color: '#fff',
    },
    timeGrid: {
        flexDirection: 'row',
        flexWrap: 'wrap',
        gap: 10,
    },
    timeSlot: {
        flex: 1,
        minWidth: '30%',
        paddingVertical: 12,
        backgroundColor: '#F8F9FA',
        borderRadius: 10,
        borderWidth: 1,
        borderColor: '#E9ECEF',
        alignItems: 'center',
    },
    timeSlotActive: {
        backgroundColor: '#2196F3',
        borderColor: '#2196F3',
    },
    timeText: {
        fontSize: 14,
        fontWeight: '500',
        color: '#495057',
    },
    editLink: {
        color: '#2196F3',
        fontWeight: 'bold',
        fontSize: 13,
    },
    formGroup: {
        marginBottom: 16,
    },
    label: {
        fontSize: 13,
        color: '#666',
        marginBottom: 8,
        fontWeight: '500',
    },
    input: {
        backgroundColor: '#F8F9FA',
        borderWidth: 1,
        borderColor: '#E9ECEF',
        borderRadius: 10,
        padding: 14,
        fontSize: 15,
        color: '#333',
    },
    inputDisabled: {
        backgroundColor: '#F1F3F5',
        color: '#999',
    },
    summaryCard: {
        backgroundColor: '#E3F2FD',
        borderRadius: 16,
        padding: 20,
        borderStyle: 'dashed',
        borderWidth: 1,
        borderColor: '#2196F3',
    },
    summaryTitle: {
        fontSize: 16,
        fontWeight: 'bold',
        color: '#1565C0',
        marginBottom: 16,
    },
    summaryRow: {
        flexDirection: 'row',
        alignItems: 'center',
        marginBottom: 12,
    },
    summaryIcon: {
        width: 20,
        marginRight: 12,
        textAlign: 'center',
    },
    summaryText: {
        fontSize: 14,
        color: '#333',
        fontWeight: '500',
    },
    footer: {
        backgroundColor: '#fff',
        padding: 20,
        paddingBottom: Platform.OS === 'ios' ? 40 : 20,
        borderTopWidth: 1,
        borderTopColor: '#F1F3F5',
    },
    confirmButton: {
        backgroundColor: '#4CAF50',
        paddingVertical: 16,
        borderRadius: 12,
        alignItems: 'center',
        shadowColor: '#4CAF50',
        shadowOffset: { width: 0, height: 4 },
        shadowOpacity: 0.3,
        shadowRadius: 8,
        elevation: 4,
    },
    confirmButtonText: {
        color: '#fff',
        fontSize: 18,
        fontWeight: 'bold',
    },
});
