import { Dimensions, StyleSheet } from 'react-native';

const { width } = Dimensions.get('window');

export const styles = StyleSheet.create({
    container: {
        flex: 1,
        backgroundColor: '#fff',
    },
    header: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
        padding: 20,
        paddingTop: 10,
        backgroundColor: '#fff',
    },
    hospitalInfo: {
        flexDirection: 'row',
        alignItems: 'center',
        gap: 12,
    },
    logoContainer: {
        width: 44,
        height: 44,
        borderRadius: 12,
        backgroundColor: '#E3F2FD',
        justifyContent: 'center',
        alignItems: 'center',
    },
    hospitalName: {
        fontSize: 12,
        fontWeight: '600',
        color: '#2196F3',
        textTransform: 'uppercase',
        letterSpacing: 0.5,
    },
    greeting: {
        fontSize: 18,
        fontWeight: 'bold',
        color: '#333',
    },
    headerIcons: {
        flexDirection: 'row',
        alignItems: 'center',
        gap: 8,
    },
    iconButton: {
        padding: 8,
        backgroundColor: '#F5F5F5',
        borderRadius: 10,
    },
    badge: {
        position: 'absolute',
        top: 8,
        right: 8,
        width: 8,
        height: 8,
        borderRadius: 4,
        backgroundColor: '#F44336',
        borderWidth: 1.5,
        borderColor: '#fff',
    },
    avatar: {
        width: 40,
        height: 40,
        borderRadius: 12,
    },
    content: {
        paddingHorizontal: 20,
        paddingBottom: 30,
    },
    searchContainer: {
        flexDirection: 'row',
        alignItems: 'center',
        backgroundColor: '#F5F7F9',
        borderRadius: 16,
        paddingHorizontal: 16,
        paddingVertical: 14,
        marginBottom: 24,
        borderWidth: 1,
        borderColor: '#EDF2F7',
    },
    searchIcon: {
        marginRight: 12,
    },
    searchInput: {
        flex: 1,
        fontSize: 16,
        color: '#333',
    },
    mainFeatures: {
        flexDirection: 'row',
        gap: 16,
        marginBottom: 24,
    },
    featureCard: {
        flex: 1,
        height: 160,
        borderRadius: 24,
        padding: 20,
        justifyContent: 'space-between',
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 4 },
        shadowOpacity: 0.1,
        shadowRadius: 12,
        elevation: 5,
    },
    featureCariDokter: {
        backgroundColor: '#2196F3',
    },
    featureBooking: {
        backgroundColor: '#4CAF50',
    },
    featureIconContainer: {
        width: 56,
        height: 56,
        borderRadius: 18,
        backgroundColor: 'rgba(255,255,255,0.2)',
        justifyContent: 'center',
        alignItems: 'center',
    },
    featureLabel: {
        fontSize: 16,
        fontWeight: 'bold',
        color: '#fff',
        lineHeight: 22,
    },
    bpjsStatusBanner: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
        backgroundColor: '#E8F5E9',
        padding: 16,
        borderRadius: 16,
        marginBottom: 24,
        borderWidth: 1,
        borderColor: '#C8E6C9',
    },
    bpjsStatusInfo: {
        flexDirection: 'row',
        alignItems: 'center',
        gap: 12,
    },
    bpjsStatusTextContainer: {
        gap: 2,
    },
    bpjsStatusLabel: {
        fontSize: 12,
        color: '#4CAF50',
    },
    bpjsActiveText: {
        fontSize: 16,
        fontWeight: 'bold',
        color: '#2E7D32',
    },
    bpjsDetailButton: {
        paddingVertical: 6,
        paddingHorizontal: 12,
        backgroundColor: '#fff',
        borderRadius: 8,
    },
    bpjsDetailText: {
        fontSize: 12,
        fontWeight: 'bold',
        color: '#2E7D32',
    },
    sectionHeader: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
        marginBottom: 16,
    },
    sectionTitle: {
        fontSize: 20,
        fontWeight: 'bold',
        color: '#1A202C',
    },
    seeAll: {
        color: '#2196F3',
        fontWeight: 'bold',
        fontSize: 14,
    },
    reminderCard: {
        flexDirection: 'row',
        alignItems: 'center',
        backgroundColor: '#FFF8E1',
        padding: 16,
        borderRadius: 20,
        marginBottom: 24,
        borderWidth: 1,
        borderColor: '#FFECB3',
    },
    reminderDateBox: {
        width: 50,
        height: 56,
        backgroundColor: '#FF9800',
        borderRadius: 12,
        justifyContent: 'center',
        alignItems: 'center',
        marginRight: 16,
    },
    reminderDay: {
        fontSize: 18,
        fontWeight: 'bold',
        color: '#fff',
    },
    reminderMonth: {
        fontSize: 10,
        fontWeight: 'bold',
        color: '#fff',
        textTransform: 'uppercase',
    },
    reminderInfo: {
        flex: 1,
        gap: 4,
    },
    reminderDoctor: {
        fontSize: 16,
        fontWeight: 'bold',
        color: '#333',
    },
    reminderTime: {
        fontSize: 13,
        color: '#666',
    },
    reminderStatus: {
        flexDirection: 'row',
        alignItems: 'center',
        gap: 4,
        backgroundColor: '#fff',
        paddingVertical: 4,
        paddingHorizontal: 8,
        borderRadius: 8,
    },
    statusDot: {
        width: 6,
        height: 6,
        borderRadius: 3,
        backgroundColor: '#4CAF50',
    },
    statusText: {
        fontSize: 10,
        fontWeight: 'bold',
        color: '#4CAF50',
    },
    horizontalScroll: {
        marginBottom: 24,
        overflow: 'visible',
    },
    quickActionCard: {
        width: 200,
        marginRight: 16,
    },
    articleCard: {
        flexDirection: 'row',
        backgroundColor: '#fff',
        borderRadius: 20,
        borderWidth: 1,
        borderColor: '#F1F5F9',
        overflow: 'hidden',
        marginBottom: 16,
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.05,
        shadowRadius: 8,
        elevation: 2,
    },
    articleImage: {
        width: 110,
        height: 110,
    },
    articleContent: {
        flex: 1,
        padding: 16,
        justifyContent: 'center',
    },
    articleTitle: {
        fontSize: 16,
        fontWeight: 'bold',
        color: '#1A202C',
        marginBottom: 6,
    },
    articleDesc: {
        fontSize: 13,
        color: '#718096',
        lineHeight: 18,
    },
    bottomSpacer: {
        height: 40,
    },
});
