import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
    container: {
        flex: 1,
        backgroundColor: '#F8F9FA',
    },
    content: {
        padding: 24,
    },
    header: {
        alignItems: 'center',
        paddingVertical: 32,
        backgroundColor: '#fff',
        borderBottomLeftRadius: 32,
        borderBottomRightRadius: 32,
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 4 },
        shadowOpacity: 0.05,
        shadowRadius: 10,
        elevation: 2,
        marginBottom: 24,
    },
    avatarContainer: {
        width: 120,
        height: 120,
        borderRadius: 60,
        backgroundColor: '#F0F7FF',
        justifyContent: 'center',
        alignItems: 'center',
        marginBottom: 16,
        position: 'relative',
    },
    editAvatarButton: {
        position: 'absolute',
        bottom: 5,
        right: 5,
        backgroundColor: '#2196F3',
        width: 32,
        height: 32,
        borderRadius: 16,
        justifyContent: 'center',
        alignItems: 'center',
        borderWidth: 3,
        borderColor: '#fff',
    },
    name: {
        fontSize: 24,
        fontWeight: 'bold',
        color: '#1A202C',
        marginBottom: 4,
    },
    email: {
        fontSize: 14,
        color: '#718096',
    },
    bpjsAlertBox: {
        flexDirection: 'row',
        alignItems: 'center',
        backgroundColor: '#FFF8E1',
        padding: 16,
        borderRadius: 16,
        marginBottom: 24,
        gap: 12,
        borderWidth: 1,
        borderColor: '#FFECB3',
    },
    bpjsAlertText: {
        flex: 1,
        fontSize: 12,
        color: '#856404',
        lineHeight: 18,
    },
    section: {
        marginBottom: 32,
    },
    sectionHeader: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
        marginBottom: 16,
    },
    sectionTitle: {
        fontSize: 18,
        fontWeight: 'bold',
        color: '#1A202C',
    },
    editButton: {
        flexDirection: 'row',
        alignItems: 'center',
        gap: 6,
    },
    editButtonText: {
        fontSize: 14,
        fontWeight: '600',
        color: '#2196F3',
    },
    infoGrid: {
        flexDirection: 'row',
        flexWrap: 'wrap',
        gap: 12,
    },
    infoCard: {
        width: '48%',
        backgroundColor: '#fff',
        padding: 16,
        borderRadius: 16,
        borderWidth: 1,
        borderColor: '#EDF2F7',
    },
    infoCardFull: {
        width: '100%',
        backgroundColor: '#fff',
        padding: 16,
        borderRadius: 16,
        borderWidth: 1,
        borderColor: '#EDF2F7',
    },
    infoLabel: {
        fontSize: 12,
        color: '#718096',
        marginBottom: 4,
    },
    infoValue: {
        fontSize: 14,
        fontWeight: '600',
        color: '#2D3748',
    },
    medicalCard: {
        backgroundColor: '#fff',
        borderRadius: 20,
        padding: 8,
        borderWidth: 1,
        borderColor: '#EDF2F7',
    },
    medicalItem: {
        flexDirection: 'row',
        alignItems: 'center',
        padding: 12,
        gap: 16,
    },
    medicalIconContainer: {
        width: 44,
        height: 44,
        borderRadius: 12,
        justifyContent: 'center',
        alignItems: 'center',
    },
    medicalInfo: {
        flex: 1,
        gap: 2,
    },
    medicalLabel: {
        fontSize: 11,
        color: '#718096',
        textTransform: 'uppercase',
        letterSpacing: 0.5,
    },
    medicalValue: {
        fontSize: 14,
        fontWeight: 'bold',
        color: '#2D3748',
    },
    bpjsCardPremium: {
        backgroundColor: '#fff',
        borderRadius: 24,
        padding: 24,
        borderLeftWidth: 8,
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 4 },
        shadowOpacity: 0.05,
        shadowRadius: 12,
        elevation: 3,
    },
    bpjsTop: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'flex-start',
        marginBottom: 20,
    },
    bpjsLogoModern: {
        width: 120,
        height: 36,
    },
    statusBadge: {
        paddingVertical: 6,
        paddingHorizontal: 12,
        borderRadius: 30,
    },
    statusBadgeText: {
        fontSize: 10,
        fontWeight: 'bold',
    },
    bpjsNumberLarge: {
        fontSize: 22,
        fontWeight: 'bold',
        color: '#1A202C',
        letterSpacing: 2,
        marginBottom: 16,
    },
    refreshBPJSButton: {
        flexDirection: 'row',
        alignItems: 'center',
        gap: 8,
        alignSelf: 'flex-start',
    },
    refreshBPJSText: {
        fontSize: 13,
        color: '#718096',
        fontWeight: '500',
    },
    settingsGroup: {
        backgroundColor: '#fff',
        borderRadius: 20,
        overflow: 'hidden',
        borderWidth: 1,
        borderColor: '#EDF2F7',
    },
    settingsItem: {
        flexDirection: 'row',
        alignItems: 'center',
        padding: 16,
        gap: 16,
        borderBottomWidth: 1,
        borderBottomColor: '#F7FAFC',
    },
    settingsIconBox: {
        width: 40,
        height: 40,
        borderRadius: 12,
        backgroundColor: '#F0F4FF',
        justifyContent: 'center',
        alignItems: 'center',
    },
    settingsLabel: {
        flex: 1,
        fontSize: 15,
        fontWeight: '600',
        color: '#4A5568',
    },
    rotating: {
        // Mock rotation handled by logic if needed or just left as static icon during dev
    },
    bottomSpacer: {
        height: 40,
    },
});
